### PR TITLE
Now each mutation in the queue is been saved into a separate file:

### PR DESCRIPTION
**Pull request by adrian1388**
'prefix''UUID'

### CODE REVIEW

**Comment by miguelocarvajal** [comment]
I understand the concept but this code should be cleaned up a bit.

I also think that instead of scanning all of the keys we can have 1 key with an array of the pending mutations. Not sure if there would be a concurrency issue with this approach.

**Comment by adrian1388** [comment]
There you have some changes, check them out and tell me is something seems wrong.

**Comment by miguelocarvajal** [comment]
Can the migration process be done when the link is initialized?

It doesn't make sense to check for the presence of an previous format every time something is processed by the link.

**Comment by adrian1388** [comment]
The migration process is done when the setup is called, only ones. It is not being processed for every mutation/retry.

I have made some clean on getQueue method.

**Pull request merged**
